import { db } from '../lib/db.js';
import { body, error, json } from '../lib/util.js';
import { isBishop } from '../lib/auth.js';
export async function listRules(request,env,user){ if(!user)return error('Unauthorized.',401); const sql=db(env); return json({rules:await sql`SELECT * FROM availability_rules WHERE active=true ORDER BY day_of_week,start_time`}); }
export async function addRule(request,env,user){ if(!isBishop(user))return error('Forbidden.',403); const d=await body(request); if(!d)return error('Invalid request.'); const sql=db(env); const r=await sql`INSERT INTO availability_rules(day_of_week,start_time,end_time,preference) VALUES(${d.day_of_week},${d.start_time},${d.end_time},${d.preference}) RETURNING *`; return json({rule:r[0]},201); }
export async function deleteRule(request,env,user,id){ if(!isBishop(user))return error('Forbidden.',403); const sql=db(env); await sql`DELETE FROM availability_rules WHERE id=${id}`; return json({ok:true}); }
export async function listOverrides(request,env,user){ if(!user)return error('Unauthorized.',401); const u=new URL(request.url); const start=u.searchParams.get('start'),end=u.searchParams.get('end'); const sql=db(env); const rows=start&&end?await sql`SELECT * FROM availability_overrides WHERE date BETWEEN ${start}::date AND ${end}::date ORDER BY date,start_time`:await sql`SELECT * FROM availability_overrides WHERE date >= current_date ORDER BY date,start_time LIMIT 100`; return json({overrides:rows}); }
export async function addOverride(request,env,user){ if(!isBishop(user))return error('Forbidden.',403); const d=await body(request); if(!d)return error('Invalid request.'); const pref=d.override_type==='add'?d.preference:null; const sql=db(env); const r=await sql`INSERT INTO availability_overrides(date,start_time,end_time,override_type,preference,note) VALUES(${d.date},${d.start_time},${d.end_time},${d.override_type},${pref},${d.note||null}) RETURNING *`; return json({override:r[0]},201); }
export async function deleteOverride(request,env,user,id){ if(!isBishop(user))return error('Forbidden.',403); const sql=db(env); await sql`DELETE FROM availability_overrides WHERE id=${id}`; return json({ok:true}); }
